In [1]:
# Q1
'''Yes, there is a difference in the data type of variables list_ and array_list. The variable list_ is a Python list, while array_list is a NumPy array.

To print the data types of both variables, you can use the type() function in Python:'''
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:
# Q2
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
# Q3
'''Yes, there will be a difference in the data type of the elements present in both variables, list_ and array_list, after applying the dtype=int argument during array creation.

In the original array_list, the elements were created with the default data type, which was numpy.str_, as shown in the previous answer. However, with the new array creation using dtype=int, the elements will be converted to integers.

Let's see the code to print the data types of each element in both list_ and the modified array_list:'''
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("\nData type of elements in modified array_list:")
for element in array_list:
    print(type(element))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in modified array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:
# Q4
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape of the array
print("Shape of num_array:", num_array.shape)

# (ii) Size of the array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [8]:
# Q5
import numpy as np
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Q6
import numpy as np
print(np.eye(5,5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
